stat_svc branch:
Vladimir01082023/java-explore-with-me pull request #1
Opened 2024-09-01 07:17 UTC by Vladimir01082023

2024-09-02 18:38 UTC, z8q requested changes

2024-09-02 18:38 UTC, z8q commented on stats-service/stats-server/pom.xml
> +            <version>42.7.3</version>
В корневом pom указываем зависимость
```XML
        <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```
Она в себе содержит информацию о версиях для списка зависимостей
можно [тут](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/3.3.2) посмотреть блок Managed Dependencies (надо вниз прокрутить)

То есть зависимости из списка, которые есть в parent мы можем указывать без версии
```XML
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
```
Если хотим добавить зависимость, которой нет в parent,
либо если хотим определенную версию, отличную от того, что предлагает parent,
то ее можно указать в корневом поме, в блоке dependencyManagement
Это позволит в дочерних pom-ах тоже не указывать версию

2024-09-02 18:38 UTC, z8q commented on stats-service/stats-server/pom.xml
> +            <version>2.2.224</version>
Про версии стоит везде посмотреть

2024-09-02 18:38 UTC, z8q commented on stats-service/stats-server/src/main/java/ru/practicum/model/Stats.java
> +@Data
Две больших статьи ([тут](https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/) и [тут](https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/)), почему ломбок с jpa-сущностями могут приводить к проблемам

Один из примеров
Если у нас есть в классе поля с FetchType == lazy (OneToMany например)
и мы запрашиваем объект из базы,
то изначально данных в lazy поле не будет,
но они могут быть дополнительно подгружены например при вызове метода toString

то есть при вызове toString могут вызываться запросы к базе

2024-09-03 17:27 UTC, z8q approved these changes

2024-09-03 17:27 UTC, z8q commented on stats-service/stats-server/pom.xml
>          <dependency>
Для hibernate-core еще осталась версия

2024-09-04 00:14 UTC, Vladimir01082023 commented on stats-service/stats-server/pom.xml
>          <dependency>
Если не указывать версию hibernate-core, то при сборке проекты выскакивает ошибка 
C:\Users\79607\.jdks\corretto-21.0.3\bin\java.exe "-Dmaven.multiModuleProjectDirectory=C:\Users\79607\Java Tasks\java-explore-with-me" -Djansi.passthrough=true "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\lib\idea_rt.jar=65054:C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.7.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2024.1\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2024.1 clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-core:jar is missing. @ line 67, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project ru.practicum:stats-server:0.0.1-SNAPSHOT (C:\Users\79607\Java Tasks\java-explore-with-me\stats-service\stats-server\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.hibernate:hibernate-core:jar is missing. @ line 67, column 21

2024-09-04 00:15 UTC, merged